language: java
jdk:
 - oraclejdk8

deploy:
 provider: heroku
 api_key:
  secure: 00b2aadb-407c-47d2-a761-c09a6a8c0008
 app: mantenimiento1718
 on:
  repo: AlbaAM/RedSocial
  branch: herokuapp
  
notifications:
 slack:
  rooms:
   - equipo1-redsocial:gHtgV5g6eQM5DkxGobKNoNIx#general
